Fix broken docs build with sphinx 7.2
AttributeError: partially initialized module 'testinfra' has no
attribute 'backend' (most likely due to a circular import)

Do be investiguated.